apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/jenkins-x-apps/jx-app-test-lifecycle:{{.VERSION}}"
  artifacts:
  - imageName: jenkins-x-apps/jx-app-test-lifecycle
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/jenkins-x-apps/jx-app-test-lifecycle:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: jx-app-test-lifecycle
        chartPath: charts/jx-app-test-lifecycle
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/jenkins-x-apps/jx-app-test-lifecycle"
          image.tag: "{{.DIGEST_HEX}}"
